### PR TITLE
Fix runtime dependency

### PR DESCRIPTION
**Pull request by HeywardLiu**
Downgrade Python version of Dockerfile.crawling from 3.11.1 to 3.8.10 ;
Change mongo version from latest to 7.0-rc

### CODE REVIEW

**Comment by Laxiflora** [comment]
review la

**Review by vivian96385 — COMMENTED** [review]
review?

**Review by vivian96385 — APPROVED** [review]

**Review by yuko29 — APPROVED** [review]
Change crawling python version and db version.
Test pass.

**Review by Laxiflora — COMMENTED** [review]
## Summary
1. change the python version in Dockerfile.crawling from 3.11.1 to 3.8.10
2. change the mongo image version from latest to 7.0-rc

@HeywardLiu  you sure this setting can run right?

**Pull request merged**
